// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLSXtoY1bomNA70q8JzNMDQfw4KpZ75k',
    appId: '1:75656697687:web:293a9cfbc58bb6d4e01012',
    messagingSenderId: '75656697687',
    projectId: 'line-pre-assessment',
    authDomain: 'line-pre-assessment.firebaseapp.com',
    storageBucket: 'line-pre-assessment.appspot.com',
    measurementId: 'G-6TYNVCXPMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJaFUUARG69QrGLVwhaXDPmKnwTB2AabI',
    appId: '1:75656697687:android:69ff358bdc5f748fe01012',
    messagingSenderId: '75656697687',
    projectId: 'line-pre-assessment',
    storageBucket: 'line-pre-assessment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3YG2_ZjlrrVNwBy_djUNuVXKuGdmJRc',
    appId: '1:75656697687:ios:6c0ce677a4960cf7e01012',
    messagingSenderId: '75656697687',
    projectId: 'line-pre-assessment',
    storageBucket: 'line-pre-assessment.appspot.com',
    iosBundleId: 'com.example.preAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi3YG2_ZjlrrVNwBy_djUNuVXKuGdmJRc',
    appId: '1:75656697687:ios:6c0ce677a4960cf7e01012',
    messagingSenderId: '75656697687',
    projectId: 'line-pre-assessment',
    storageBucket: 'line-pre-assessment.appspot.com',
    iosBundleId: 'com.example.preAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdLSXtoY1bomNA70q8JzNMDQfw4KpZ75k',
    appId: '1:75656697687:web:0a17781569a37961e01012',
    messagingSenderId: '75656697687',
    projectId: 'line-pre-assessment',
    authDomain: 'line-pre-assessment.firebaseapp.com',
    storageBucket: 'line-pre-assessment.appspot.com',
    measurementId: 'G-66WHW23XZL',
  );
}

// Platform  Firebase App Id
// web       1:75656697687:web:293a9cfbc58bb6d4e01012
// android   1:75656697687:android:69ff358bdc5f748fe01012
// ios       1:75656697687:ios:6c0ce677a4960cf7e01012
// macos     1:75656697687:ios:6c0ce677a4960cf7e01012
// windows   1:75656697687:web:0a17781569a37961e01012